# Site settings
baseurl: ""

title: "Clínica Dental República Argentina"
desc: "Clínica Dental República Argentina Córdoba"
url: "http://www.example.com"

description: "Clínica Dental República Argentina Córdoba"
email: "clinicadental.ra@gmail.com"
phone: "(+34) 957 044 644"
location: "Avd. República Argentina, nº 24.<br/> 14004, Córdoba"

linkedin:  "https://www.linkedin.com/company/gooveris"
facebook: "https://www.facebook.com/tenispadelsevilla"
twitter: "https://twitter.com/gooveris"

# Build settings
markdown: kramdown
permalink: pretty